export const selPDFViewStyles = {
	dialogPaper: {
		borderRadius: '10px',
		// minWidth: '550px',
		// width: '100%',
		// maxWidth: '50vw',
		maxHeight: '95vh',
		padding: '20px 30px',
		display: 'flex',
		flexDirection: 'column',
	},
	headerBox: {
		pb: '12px',
		display: 'flex',
		flexDirection: 'row',
		justifyContent: 'space-between',
		alignItems: 'center',
		position: 'sticky',
		top: 0,
		backgroundColor: 'white',
		zIndex: 1,
	},
	title: {
		fontWeight: 500,
		color: 'textColors.black',
		fontSize: '18px',
	},
	coloredTitle: {
		fontWeight: 500,
		fontSize: '18px',
		color: 'globalElementColors.blue',
		cursor: 'pointer',
	},
	titleBox: { display: 'flex', flexDirection: 'row', gap: '5px' },
	zoomControls: {
		display: 'flex',
		justifyContent: 'center',
		gap: 1,
		mt: 1,
	},
	zoomText: {
		alignSelf: 'center',
		minWidth: '40px',
		display: 'flex',
		justifyContent: 'center',
	},
	scrollContainer: {
		// mt: '10px',
		height: 'calc(95vh - 140px)',
		overflowY: 'auto',
		position: 'relative',
		'&::-webkit-scrollbar': {
			width: '7px',
		},
		'&::-webkit-scrollbar-thumb:hover': {
			background: '#555',
		},
		'& .react-pdf__message': {
			display: 'none',
		},
	},
	pageWrapper: {
		marginBottom: '20px',
		display: 'flex',
		justifyContent: 'center',
	},
	pageNumber: {
		position: 'sticky',
		bottom: 0,
		right: 0,
		textAlign: 'right',
		px: 2,
		py: 1,
		backgroundColor: 'white',
		zIndex: 1,
	},
	iconStyle: {
		cursor: 'pointer',
		width: '32px',
		height: '32px',
	},
	fileItem: {
		display: 'flex',
		alignItems: 'center',
		gap: '10px',
		padding: '8px 0',
		cursor: 'pointer',
		color: 'globalElementColors.blue',
	},
	pdfViewer: {
		width: '100%',
		height: '70vh',
		border: 'none',
	},
	nodataStyles: {
		display: 'flex',
		flexDirection: 'column',
		justifyContent: 'center',
		alignItems: 'center',
		gap: '10px',
	},
}
