import { localizationConstants } from '../../../resources/theme/localizationConstants'
import { sortEnum } from '../../../utils/utils'
import { requestParams } from '../../../utils/apiConstants'

export const initialStudentState = {
	studentName: '',
	className: '',
	section: '',
	regNo: '',
	nationality: '',
	bloodGrp: '',
	fatherName: '',
	motherName: '',
	phone: '',
	gender: '',
	email: '',
	school: '',
}

export const initialStudentErrors = {
	studentName: false,
	className: false,
	section: false,
	regNo: false,
	phone: false,
	gender: false,
	email: false,
}

export const genderOptions = ['Male', 'Female']

export const validateStudentKeys = [
	'studentName',
	'className',
	'section',
	'regNo',
	'gender',
]

export const studentUploadDefaultExcelColumns = [
	{
		'Student ID': '',
		Classroom: '',
		Section: '',
		'Student Name': '',
		Reg_no: '',
		Reg_date: '',
		Nationality: '',
		DOB: '',
		Gender: '',
		Blood_group: '',
		'Father Name': '',
		'Mother Name': '',
		Email: '',
		Phone_no: '',
		profilePicture: '',
		profilePicUrl: '',
	},
]

export const studentsColumn = [
	{
		id: localizationConstants.id,
		name: 'user_id',
		label: localizationConstants.id,
		numeric: false,
		dataCount: false,
		disablePadding: false,
		sort: sortEnum.desc,
		align: localizationConstants.left,
		width: 70,
	},
	{
		id: localizationConstants.studentsName,
		name: 'studentName',
		label: localizationConstants.studentsName,
		numeric: false,
		dataCount: false,
		disablePadding: false,
		sort: sortEnum.desc,
		align: localizationConstants.left,
		width: 130,
	},
	{
		id: localizationConstants.schoolName,
		name: 'school',
		label: localizationConstants.schoolName,
		numeric: false,
		dataCount: false,
		disablePadding: false,
		sort: sortEnum.desc,
		align: localizationConstants.left,
		width: 140,
	},
	{
		id: localizationConstants.academicYear,
		name: 'academicYear',
		label: localizationConstants.academicYear,
		numeric: false,
		dataCount: false,
		disablePadding: false,
		sort: sortEnum.desc,
		align: localizationConstants.left,
		width: 85,
	},
	{
		id: localizationConstants.status,
		name: 'status',
		label: localizationConstants.status,
		numeric: false,
		dataCount: false,
		disablePadding: false,
		sort: sortEnum.desc,
		align: localizationConstants.left,
		width: 75,
	},
	{
		id: localizationConstants.className,
		name: 'className',
		label: localizationConstants.className,
		numeric: false,
		dataCount: false,
		disablePadding: false,
		sort: sortEnum.desc,
		align: localizationConstants.left,
		width: 70,
	},
	{
		id: localizationConstants.section,
		name: 'section',
		label: localizationConstants.section,
		numeric: false,
		dataCount: false,
		disablePadding: false,
		sort: sortEnum.desc,
		align: localizationConstants.left,
		width: 70,
	},
	{
		id: localizationConstants.registrationNumber,
		name: 'regNo',
		label: localizationConstants.registrationNumber,
		numeric: false,
		dataCount: false,
		disablePadding: false,
		sort: sortEnum.desc,
		align: localizationConstants.left,
		width: 100,
	},
	{
		id: localizationConstants.mobileNum,
		name: 'phone',
		label: localizationConstants.mobileNum,
		numeric: false,
		dataCount: false,
		disablePadding: false,
		sort: sortEnum.desc,
		align: localizationConstants.left,
		width: 110,
	},
	{
		id: localizationConstants.nationality,
		name: 'nationality',
		label: localizationConstants.nationality,
		numeric: false,
		dataCount: false,
		disablePadding: false,
		sort: sortEnum.desc,
		align: localizationConstants.left,
		width: 90,
	},
	{
		id: localizationConstants.registrationDate,
		name: 'regDate',
		label: localizationConstants.registrationDate,
		numeric: false,
		dataCount: false,
		disablePadding: false,
		sort: sortEnum.desc,
		align: localizationConstants.left,
		width: 100,
	},
	{
		id: localizationConstants.gender,
		name: 'gender',
		label: localizationConstants.gender,
		numeric: false,
		dataCount: false,
		disablePadding: false,
		sort: sortEnum.desc,
		align: localizationConstants.left,
		width: 70,
	},
	{
		id: localizationConstants.dob,
		name: 'dob',
		label: localizationConstants.dob,
		numeric: false,
		dataCount: false,
		disablePadding: false,
		sort: sortEnum.desc,
		align: localizationConstants.left,
		width: 90,
	},
	{
		id: localizationConstants.bloodGroup,
		name: 'bloodGrp',
		label: localizationConstants.bloodGroup,
		numeric: false,
		dataCount: false,
		disablePadding: false,
		sort: sortEnum.desc,
		align: localizationConstants.left,
		width: 70,
	},
	{
		id: localizationConstants.fathersName,
		name: 'fatherName',
		label: localizationConstants.fathersName,
		numeric: false,
		dataCount: false,
		disablePadding: false,
		sort: sortEnum.desc,
		align: localizationConstants.left,
		width: 120,
	},
	{
		id: localizationConstants.mothersName,
		name: 'motherName',
		label: localizationConstants.mothersName,
		numeric: false,
		dataCount: false,
		disablePadding: false,
		sort: sortEnum.desc,
		align: localizationConstants.left,
		width: 120,
	},
]

export const studentsColumnForSectionShift = [
	{
		id: localizationConstants.id,
		name: 'user_id',
		label: localizationConstants.id,
		numeric: false,
		dataCount: false,
		disablePadding: false,
		sort: sortEnum.desc,
		align: localizationConstants.left,
		width: 90,
	},
	{
		id: localizationConstants.studentsName,
		name: 'studentName',
		label: localizationConstants.studentsName,
		numeric: false,
		dataCount: false,
		disablePadding: false,
		sort: sortEnum.desc,
		align: localizationConstants.left,
		width: 140,
	},
	{
		id: localizationConstants.section,
		name: 'section',
		label: localizationConstants.section,
		numeric: false,
		dataCount: false,
		disablePadding: false,
		sort: sortEnum.desc,
		align: localizationConstants.left,
		width: 80,
	},
	{
		id: localizationConstants.registrationNumber,
		name: 'regNo',
		label: localizationConstants.registrationNumber,
		numeric: false,
		dataCount: false,
		disablePadding: false,
		sort: sortEnum.desc,
		align: localizationConstants.left,
		width: 130,
	},
	{
		id: localizationConstants.registrationDate,
		name: 'registrationDate',
		label: localizationConstants.registrationDate,
		numeric: false,
		dataCount: false,
		disablePadding: false,
		sort: sortEnum.desc,
		align: localizationConstants.left,
		width: 120,
	},
]

export const sortkeys = [
	{
		[requestParams.key]: 'user_id',
		[requestParams.value]: sortEnum.asc,
	},

	{
		[requestParams.key]: 'studentName',
		[requestParams.value]: sortEnum.asc,
	},
	{
		[requestParams.key]: 'school',
		[requestParams.value]: sortEnum.asc,
	},
	{
		[requestParams.key]: 'academicYear',
		[requestParams.value]: sortEnum.asc,
	},
	{
		[requestParams.key]: 'status',
		[requestParams.value]: sortEnum.asc,
	},
	{
		[requestParams.key]: 'className',
		[requestParams.value]: sortEnum.asc,
	},
	{
		[requestParams.key]: 'section',
		[requestParams.value]: sortEnum.asc,
	},
	{
		[requestParams.key]: 'regNo',
		[requestParams.value]: sortEnum.asc,
	},
	{
		[requestParams.key]: 'phone',
		[requestParams.value]: sortEnum.asc,
	},
	{
		[requestParams.key]: 'nationality',
		[requestParams.value]: sortEnum.asc,
	},
	{
		[requestParams.key]: 'regDate',
		[requestParams.value]: sortEnum.asc,
	},
	{
		[requestParams.key]: 'gender',
		[requestParams.value]: sortEnum.asc,
	},
	{
		[requestParams.key]: 'dob',
		[requestParams.value]: sortEnum.asc,
	},
	{
		[requestParams.key]: 'bloodGrp',
		[requestParams.value]: sortEnum.asc,
	},
	{
		[requestParams.key]: 'fatherName',
		[requestParams.value]: sortEnum.asc,
	},
	{
		[requestParams.key]: 'motherName',
		[requestParams.value]: sortEnum.asc,
	},
]
