export const studentCopeStyles = {
	topBoxSx: {
		padding: '10px ',
		display: 'flex',
		justifyContent: 'center',
		flexDirection: 'column',
		alignItems: 'flex-start',
		borderRadius: '10px',
		border: '1px solid #ECECEC',
		height: '130px',
		mt: '15px',
		background: '#FFF',
	},
	questionBoxSx: {
		borderRadius: '10px',
		background: '#FFF',
		boxShadow: '0px 0px 10px 0px rgba(0, 0, 0, 0.10)',
		mt: '10px',
		padding: '20px',
		display: 'flex',
		justifyContent: 'space-between',
		flexWrap: 'wrap',
	},
	questions: {
		minHeight: '110px',
		border: '1px solid #E2E2E2',
		borderRadius: '10px',
		padding: '20px',
		display: 'flex',
		justifyContent: 'space-between',
		flexDirection: 'column',
		width: '49%',
	},
}
