import { localizationConstants } from '../../../resources/theme/localizationConstants'
import { requestParams } from '../../../utils/apiConstants'
import { sortEnum } from '../../../utils/utils'

export const invalidTest = ['', null, undefined, NaN]

export const initialStateIC = {
	studentName: '',
	user_id: '',
	academicYear: '',
	date: new Date(),
	startTime: new Date(),
	endTime: '',
	issues: '',
	stype: '',
	goals: '',
	activity: '',
	purpose: '',
	description: '',
	improvements: '',
	comments: '',
	tasksAssigned: '',
	poa: '',
	basedOn: '',
	dimension: '',
	outcome: '',
}

export const initialDropdownStates = {
	schools: [],
	classrooms: [],
	sections: [],
	students: [],
}

export const typeConstants = ['Individual', 'Group']

export const basedOnConstants = ['Referral', 'Identified', 'Voluntary']

export const dimensionConstants = [
	'Physical',
	'Social',
	'Emotional',
	'Cognitive',
	'Linguistic',
]

export const outcomeConstants = [
	'Achieved',
	'Not-Achieved',
	'Achieved with assistance',
]

export const individualCaseColumn = [
	{
		id: localizationConstants.id,
		name: 'user_id',
		label: localizationConstants.id,
		numeric: false,
		dataCount: false,
		disablePadding: false,
		sort: sortEnum.asc,
		align: localizationConstants.left,
		width: 70,
	},
	{
		id: localizationConstants.academicYear,
		name: 'academicYear',
		label: localizationConstants.academicYear,
		numeric: false,
		dataCount: false,
		disablePadding: false,
		sort: sortEnum.asc,
		align: localizationConstants.left,
		width: 90,
	},
	{
		id: localizationConstants.studentsName,
		name: 'studentName',
		label: localizationConstants.studentsName,
		numeric: false,
		dataCount: false,
		disablePadding: false,
		sort: sortEnum.asc,
		align: localizationConstants.left,
		width: 130,
	},
	{
		id: localizationConstants.date,
		name: 'date',
		label: localizationConstants.date,
		numeric: false,
		dataCount: false,
		disablePadding: false,
		sort: sortEnum.desc,
		align: localizationConstants.left,
		width: 100,
	},
	{
		id: 'createdAt',
		name: 'createdAt',
		label: 'Created Date',
		numeric: false,
		dataCount: false,
		disablePadding: false,
		sort: sortEnum.asc,
		align: localizationConstants.left,
		width: 100,
	},
	{
		id: localizationConstants.startTime,
		name: 'startTime',
		label: localizationConstants.startTime,
		numeric: false,
		dataCount: false,
		disablePadding: false,
		align: localizationConstants.left,
		width: 80,
	},
	{
		id: localizationConstants.endTime,
		name: 'endTime',
		label: localizationConstants.endTime,
		numeric: false,
		dataCount: false,
		disablePadding: false,
		align: localizationConstants.left,
		width: 80,
	},
	{
		id: localizationConstants.issueReported,
		name: 'issues',
		label: localizationConstants.issueReported,
		numeric: false,
		dataCount: false,
		disablePadding: false,
		align: localizationConstants.left,
		width: 150,
	},
	{
		id: localizationConstants.goals,
		name: 'goals',
		label: localizationConstants.goals,
		numeric: false,
		dataCount: false,
		disablePadding: false,
		align: localizationConstants.left,
		width: 150,
	},
	{
		id: localizationConstants.activity,
		name: 'activity',
		label: localizationConstants.activity,
		numeric: false,
		dataCount: false,
		disablePadding: false,
		align: localizationConstants.left,
		width: 150,
	},
	{
		id: localizationConstants.dimension,
		name: 'dimension',
		label: localizationConstants.dimension,
		numeric: false,
		dataCount: false,
		disablePadding: false,
		align: localizationConstants.left,
		width: 100,
	},
	{
		id: localizationConstants.description,
		name: 'description',
		label: localizationConstants.description,
		numeric: false,
		dataCount: false,
		disablePadding: false,
		align: localizationConstants.left,
		width: 180,
	},
	{
		id: localizationConstants.type,
		name: 'stype',
		label: localizationConstants.type,
		numeric: false,
		dataCount: false,
		disablePadding: false,
		align: localizationConstants.left,
		width: 90,
	},
	{
		id: localizationConstants.basedOn,
		name: 'basedOn',
		label: localizationConstants.basedOn,
		numeric: false,
		dataCount: false,
		disablePadding: false,
		align: localizationConstants.left,
		width: 100,
	},
	{
		id: localizationConstants.purpose,
		name: 'purpose',
		label: localizationConstants.purpose,
		numeric: false,
		dataCount: false,
		disablePadding: false,
		align: localizationConstants.left,
		width: 150,
	},
	{
		id: localizationConstants.outcome,
		name: 'outcome',
		label: localizationConstants.outcome,
		numeric: false,
		dataCount: false,
		disablePadding: false,
		align: localizationConstants.left,
		width: 120,
	},
	{
		id: localizationConstants.improvementAreas,
		name: 'improvements',
		label: localizationConstants.improvementAreas,
		numeric: false,
		dataCount: false,
		disablePadding: false,
		align: localizationConstants.left,
		width: 150,
	},
	{
		id: localizationConstants.comments,
		name: 'comments',
		label: localizationConstants.comments,
		numeric: false,
		dataCount: false,
		disablePadding: false,
		align: localizationConstants.left,
		width: 180,
	},
	{
		id: localizationConstants.taskAssigned,
		name: 'tasksAssigned',
		label: localizationConstants.taskAssigned,
		numeric: false,
		dataCount: false,
		disablePadding: false,
		align: localizationConstants.left,
		width: 150,
	},
	{
		id: localizationConstants.poa,
		name: 'poa',
		label: localizationConstants.poa,
		numeric: false,
		dataCount: false,
		disablePadding: false,
		align: localizationConstants.left,
		width: 180,
	},
	{
		id: localizationConstants.showCategoryActions,
		name: 'actions',
		label: '',
		width: 160,
	},
]

export const sortkeys = [
	{
		[requestParams.key]: 'user_id',
		[requestParams.value]: sortEnum.asc,
	},
	{
		[requestParams.key]: 'academicYear',
		[requestParams.value]: sortEnum.asc,
	},
	{
		[requestParams.key]: 'studentName',
		[requestParams.value]: sortEnum.asc,
	},
	{
		[requestParams.key]: 'date',
		[requestParams.value]: sortEnum.desc,
	},
]
